# Default values for tgi-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

modelName: meta-llama/Llama-2-70b-chat-hf

hostVolumePath: /scratch-2/data

shard: 
  sharded: true
  numshard: 2

hgtoken: 
  tokenRequired: true
  token: 

image:
  repository: docker.io/rramamu1/tgi_gaudi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.2"

service:
  type: ClusterIP
  port: 8080

resources:
  numofgaudi: 2
  hugepages2Mi: 3600Mi
  cpu: 25
  memory: 168G

