apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
        path: /{{ .Release.Name }}(/|$)(.*)
        pathType: ImplementationSpecific
        #pathType: Prefix
