# Default values for tgi-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

modelName: mistralai/Mistral-7B-Instruct-v0.1

hostVolumePath: /scratch-1/data

image:
  repository: docker.io/rramamu1/std-gaudi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

resources:
  numofgaudi: 1
  hugepages2Mi: 500Mi
  cpu: 10
  memory: 60G

